### ISSUE TITLE
Can't get internal metrics from carbonapi and carbonzipper

### ISSUE THREAD

**Issue by BorisMan9** [bookingcom/carbonapi#503]
in my config yaml (both for carbonapi and carbonzipper) I configured the internal metrics prop:
```
graphite:
  host: "localhost:2003"
  interval: "60s"
  prefix: "carbon.api" // ("carbon.zipper" for carbonzipper)
  pattern: "{prefix}.{fqdn}"
```

but the internal metrics are not created
