### ISSUE TITLE
Caching despite low threshold

### ISSUE THREAD

**Issue by gerases** [bookingcom/carbonapi#538]
Hi,

I have the following caching configuration now:

```
cache:
   # Type of caching. Valid: "mem", "memcache", "null"
   type: "mem"
   # Cache limit in megabytes
   size_mb: 0
   # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
   defaultTimeoutSec: 10
```

Despite that, the new metrics are not discovered until about 30 minutes later. Is there something I'm missing in the configuration? What's a good way to troubleshoot this?

Thanks!

**Comment by deniszh** [comment]
If you think it's a cache issue - switch cache type to "null". I think 0 mb cache means "unlimited". Also, if you using go-carbon realtime metric discovery will work only if using carbonserver with realtime-index enabled. Otherwise new metric will become visible only after file is created, which can be delayed because of disk load or low max-creates-per-second value.

**Comment by gerases** [comment]
Thanks for the super quick reply. I will try null. I do seem to be using go-carbon (i inherited the cluster, so bear with me):

```
   backendsv2:
        backends:
          -
            groupName: "go-carbon"
            # supported:
            #    carbonapi_v2_pb - carbonapi 0.11 or earlier version of protocol.
            #    carbonapi_v3_pb - new protocol, http interface (native)
            #    carbonapi_v3_grpc - new protocol, gRPC interface (native)
            #    protobuf, pb, pb3 - same as carbonapi_v2_pb
            #    msgpack - protocol used by graphite-web 1.1 and metrictank
            #    auto - carbonapi will do it's best to guess if it's carbonapi_v3_pb or carbonapi_v2_pb
            #
            #  non-native protocols will be internally converted to new protocol, which will increase memory consumption
            protocol: "carbonapi_v3_pb"
           servers:
                - "http://some-host:8081"
                ...
```

By `carbonserver` do you mean the go-carbon service?

Legacy graphite service does see the metrics almost immediately though. So the files are definitely there.
